# Настройки ORM
datasource:
  # Задаём базу данных, к которой будет происходить подключение
  db:
    username: "sa"
    password: ""
    url: "jdbc:h2:./sam_serdiukov"

ebean:
  db:
    migration:
      run: true
  #      generate: true
  #      seedSql: seed.sql

#  # Настраиваем консоль Н2
#  # Это позволит нам открыть её в браузере по указанному пути
#  h2:
#    console:
#      enabled: true
#      # Указываем путь, по которому будет открываться консоль
#      path: /h2console/
#      settings:
#        web-allow-others: true