# Настройки ORM
datasource:
  # Задаём базу данных, к которой будет происходить подключение
  db:
    username: "sa"
    password: "sa"
    url: "jdbc:h2:./sam_serdiukov"

ebean:
  db:
    migration:
      run: true
